=== schwitzkroko/net.ifao.oomph.setup.buildship/ifao-plugin/net.ifao.plugin/src/net/ifao/plugins/Swt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<!-- Mit XMLSpy v2005 rel. 3 U bearbeitet (http://www.altova.com) von Bernd Ziegler (i:FAO Aktiengesellschaft) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SWT">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element name="Shell">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Composite" type="CompositeType"/>
						</xs:sequence>
						<xs:attribute name="name"/>
						<xs:attribute name="background" type="BackgroundType"/>
						<xs:attribute name="modal" type="xs:boolean" default="true"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Composite" type="CompositeType"/>
			</xs:choice>
			<xs:attribute name="package" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CompositeType">
		<xs:complexContent>
			<xs:extension base="CompositeBaseType">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Composite" type="CompositeType" minOccurs="0"/>
					<xs:element name="Label" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="Button" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="CompositeBaseType">
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="DEFAULT"/>
												<xs:enumeration value="CHECK"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="checked" type="xs:boolean"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="Tree" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="Text" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="List" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="Canvas" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="Combo" type="CompositeBaseType" minOccurs="0"/>
					<xs:element name="Group" type="CompositeType" minOccurs="0"/>
					<xs:element name="SashForm" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="CompositeType">
									<xs:attribute name="sashDirection" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="HORIZONTAL"/>
												<xs:enumeration value="VERTICAL"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="TabFolder" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="CompositeBaseType">
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="TabItem" type="CompositeType" minOccurs="0"/>
									</xs:sequence>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="numColumns"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CompositeBaseType">
		<xs:sequence>
			<xs:element name="Menu" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="CompositeBaseType">
							<xs:sequence>
								<xs:element name="MenuItem" type="CompositeBaseType" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="border" default="NONE">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NONE"/>
					<xs:enumeration value="BORDER"/>
					<xs:enumeration value="SHADOW_ETCHED_IN"/>
					<xs:enumeration value="SHADOW_ETCHED_OUT"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="colSpan"/>
		<xs:attribute name="rowSpan"/>
		<xs:attribute name="fill" default="NONE">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NONE"/>
					<xs:enumeration value="VERTICAL"/>
					<xs:enumeration value="HORIZONTAL"/>
					<xs:enumeration value="FULL"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="background" type="BackgroundType" default="NONE"/>
		<xs:attribute name="text" type="xs:string"/>
		<xs:attribute name="font">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="HEADER_FONT"/>
					<xs:enumeration value="BANNER_FONT"/>
					<xs:enumeration value="DEFAULT_FONT"/>
					<xs:enumeration value="TEXT_FONT"/>
					<xs:enumeration value="DIALOG_FONT"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="enabled" type="xs:boolean"/>
		<xs:attribute name="image"/>
	</xs:complexType>
	<xs:simpleType name="BackgroundType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE"/>
			<xs:enumeration value="COLOR_LIST_BACKGROUND"/>
			<xs:enumeration value="COLOR_WIDGET_BACKGROUND"/>
			<xs:enumeration value="COLOR_WIDGET_LIGHT_SHADOW"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifao-plugin/net.ifao.plugin/src/net/ifao/plugins/dialog/InputCombo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Swt.xsd" package="net.ifao.plugins.dialog">
	<Shell name="Select" background="COLOR_LIST_BACKGROUND">
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_LIST_BACKGROUND">
			<Composite fill="FULL" background="COLOR_LIST_BACKGROUND">
				<Label text="Select from list below" font="HEADER_FONT"/>
				<Label name="Type" text="..." />
			</Composite>
			<Canvas image="testcase_big.png"/>
		</Composite>
		<Composite border="SHADOW_ETCHED_OUT" fill="FULL" background="COLOR_WIDGET_BACKGROUND">
			<Composite border="SHADOW_ETCHED_IN" fill="FULL" numColumns="2" background="COLOR_WIDGET_LIGHT_SHADOW">
				<Label text="Select:"/>
				<Combo name="Select" fill="HORIZONTAL" border="BORDER"/>
				<Text colSpan="2" name="Comment" fill="FULL" border="SHADOW_ETCHED_OUT" background="COLOR_WIDGET_LIGHT_SHADOW"/>
			</Composite>
		</Composite>
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_WIDGET_BACKGROUND">
			<Composite fill="FULL">
			</Composite>
			<Composite numColumns="2">
				<Button name="Finish" text="  OK  " enabled="false" fill="HORIZONTAL"/>
				<Button name="Cancel" text="  Cancel  " fill="HORIZONTAL"/>
			</Composite>
		</Composite>
	</Shell>
</SWT>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifaoPlugin/src/net/ifao/plugins/dialog/InputText.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Swt.xsd" package="net.ifao.tools.plugins.dialog">
	<Shell name="Select" background="COLOR_LIST_BACKGROUND">
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_LIST_BACKGROUND">
			<Composite fill="FULL" background="COLOR_LIST_BACKGROUND">
				<Label name="Header"  text="Enter your text" font="HEADER_FONT"/>
				<Label name="Type" text="..." />
			</Composite>
			<Canvas image="testcase_big.png"/>
		</Composite>
		<Composite border="SHADOW_ETCHED_OUT" fill="FULL" background="COLOR_WIDGET_BACKGROUND">
				<Text name="Input" fill="FULL" border="BORDER"/>
		</Composite>
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_WIDGET_BACKGROUND">
			<Composite fill="FULL">
			</Composite>
			<Composite numColumns="2">
				<Button name="Finish" text="  OK  " enabled="false" fill="HORIZONTAL"/>
				<Button name="Cancel" text="  Cancel  " fill="HORIZONTAL"/>
			</Composite>
		</Composite>
	</Shell>
</SWT>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifao-plugin/net.ifao.plugin/src/net/ifao/plugins/editor/testcase/JUnitWait.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Swt.xsd" package="net.ifao.plugins.editor.testcase">
	<Shell name="Execute JUnit" background="COLOR_WIDGET_BACKGROUND" modal="false">
		<Composite numColumns="2" fill="FULL">
			<Label text="Package:"/>
			<Text name="Package" fill="HORIZONTAL" enabled="false"/>
			<Label text="Testcase:"/>
			<Text name="Testcase" fill="HORIZONTAL" enabled="false"/>
			<Text colSpan="2" name="Detail" fill="FULL"/>
			<Composite colSpan="2" numColumns="3" fill="HORIZONTAL">
				<Button name="ExamDiff" enabled="false" image="examdiff.gif"/>
				<Composite fill="FULL"/>
				<Button name="OK" text="  OK  " enabled="false"/>
			</Composite>
		</Composite>
	</Shell>
</SWT>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifao-plugin/ifaoPlugin/src/net/ifao/plugins/editor/testcase/AddTestcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Swt.xsd" package="net.ifao.plugins.editor.testcase">
	<Shell name="Add TestCase" background="COLOR_LIST_BACKGROUND">
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_LIST_BACKGROUND">
			<Composite fill="FULL" background="COLOR_LIST_BACKGROUND">
				<Label text="Create a new Testcase" font="HEADER_FONT"/>
				<Label text="Select a new Template or create from existing one"/>
			</Composite>
			<Canvas image="testcase_big.png"/>
		</Composite>
		<Composite border="SHADOW_ETCHED_OUT" fill="FULL" background="COLOR_WIDGET_BACKGROUND">
			<Composite border="SHADOW_ETCHED_IN" fill="FULL" numColumns="2" background="COLOR_WIDGET_LIGHT_SHADOW">
				<Label text="Name:"/>
				<Text name="TestCaseName" fill="HORIZONTAL" border="BORDER"/>
				<Button name="Check" text="Use from existing template:" checked="false" colSpan="2" type="CHECK"/>
				<List name="Templates" colSpan="2" fill="FULL" border="BORDER" enabled="false"/>
				<Text name="Detail" colSpan="2" fill="FULL" border="SHADOW_ETCHED_OUT" background="COLOR_WIDGET_LIGHT_SHADOW"/>
			</Composite>
		</Composite>
		<Composite numColumns="2" fill="HORIZONTAL" background="COLOR_WIDGET_BACKGROUND">
			<Composite fill="FULL">
			</Composite>
			<Composite numColumns="2">
				<Button name="Finish" text="  OK  " enabled="false" fill="HORIZONTAL"/>
				<Button name="Cancel" text="  Cancel  " fill="HORIZONTAL"/>
			</Composite>
		</Composite>
	</Shell>
</SWT>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifaoPlugin/src/net/ifao/plugins/editor/testcase/Testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Swt.xsd" package="net.ifao.plugins.editor.testcase">
	<Composite fill="FULL" background="COLOR_LIST_BACKGROUND">
		<Composite numColumns="2" fill="HORIZONTAL">
			<Label name="Title" text="TestObject:" font="HEADER_FONT" fill="HORIZONTAL"/>
			<Label name="Type" text="Type:" font="BANNER_FONT"/>
		</Composite>
		<SashForm fill="FULL" sashDirection="HORIZONTAL">
			<Group text="Testcases" fill="FULL" numColumns="2" font="BANNER_FONT">
				<Tree name="Testcases" fill="FULL">
					<Menu name="TestcaseMenu">
						<MenuItem name="MenuPre" text="Add new precondition ..." image="precondition.gif"/>
						<MenuItem name="MenuValid" text="Add new expecation ..." image="validator.gif"/>
						<MenuItem/>
						<MenuItem name="ActivateAllTestcases" text="Activate all testcases" image="testcase.gif"/>
						<MenuItem name="ActivateTestcase" text="Activate testcase" image="testcase.gif"/>
						<MenuItem name="DisableTestcase" text="Disable testcase" image="testcaseDisabled.gif"/>
						<MenuItem/>
						<MenuItem name="MenuRunTestcase" text="Run as JUnit-Test" image="junit.gif"/>
						<MenuItem name="MenuAdd2Template" text="Add Testcase to Template"/>
					</Menu>
				</Tree>
				<Composite fill="VERTICAL">
					<Button name="TCAdd" text="Add ..." fill="HORIZONTAL"/>
					<Button name="TCDelete" text="Delete" fill="HORIZONTAL" enabled="false"/>
					<Button name="TCCopy" text="Copy" fill="HORIZONTAL" enabled="false"/>
					<Button name="TCPaste" text="Paste" fill="HORIZONTAL"/>
					<Button name="TCUp" text="Up" fill="HORIZONTAL"/>
					<Button name="TCDown" text="Down" fill="HORIZONTAL"/>
					<Composite fill="FULL"/>
					<Button name="TCRun" text="Run" fill="HORIZONTAL" image="junit.gif"/>
					<Button name="TCSrc" text="Src" fill="HORIZONTAL" image="javaSrc.gif"/>
				</Composite>
			</Group>
			<Group name="Detail" text="Testcase detail" fill="FULL" font="BANNER_FONT">
				<Composite fill="FULL">
  			    </Composite>
				<Composite numColumns="2" fill="FULL">
					<Label text="Set the properties for selected Testcase" colSpan="2"/>
					<Label text="Name:"/>
					<Text name="NameCase" fill="HORIZONTAL"/>
					<Label text="Description:" fill="HORIZONTAL" colSpan="2"/>
					<Text name="DescriptionCase" fill="FULL" colSpan="2"/>
				</Composite>
				<Composite numColumns="2" fill="FULL">
					<Label text="Class:"/>
					<Text name="CompClass" fill="HORIZONTAL" border="NONE"/>
					<Label colSpan="2" text="Description:"/>
					<Text colSpan="2" name="CompDesc" fill="FULL" border="SHADOW_ETCHED_OUT" background="COLOR_WIDGET_LIGHT_SHADOW"/>
				</Composite>
				<Composite fill="FULL">
					<Label name="DetailText" text="Detail Value ..." fill="HORIZONTAL"/>
					<Composite fill="HORIZONTAL">
						<Text name="DetailDesc" fill="FULL" border="SHADOW_ETCHED_OUT" background="COLOR_WIDGET_LIGHT_SHADOW"/>
					</Composite>
					<Text name="Detail" fill="FULL"/>
				</Composite>
			</Group>
		</SashForm>
	</Composite>
</SWT>

=== schwitzkroko/net.ifao.oomph.setup.buildship/ifao-plugin/net.ifao.plugin/src/net/ifao/plugins/editor/dtdinfo/DtdInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML-Beispieldatei von XMLSpy generiert v2005 rel. 3 U (http://www.altova.com)-->
<SWT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Swt.xsd" package="net.ifao.plugins.editor.dtdinfo">
	<Shell name="DtdInfo" background="COLOR_WIDGET_BACKGROUND" modal="true">
		<Composite fill="FULL" background="COLOR_WIDGET_LIGHT_SHADOW">
			<Label name="Title" text="Title:" font="HEADER_FONT"/>
			<SashForm name="Sash" sashDirection="HORIZONTAL" fill="FULL">
				<Composite fill="FULL" border="SHADOW_ETCHED_OUT" background="COLOR_WIDGET_BACKGROUND">
					<TabFolder name="ReqRes" fill="FULL">
						<TabItem  text="Request" background="COLOR_LIST_BACKGROUND">
							<Composite>
								<Tree name="Req" fill="FULL" background="COLOR_LIST_BACKGROUND"/>
							</Composite>
						</TabItem>
						<TabItem  text="Response" background="COLOR_LIST_BACKGROUND">
							<Composite>
								<Tree name="Res" fill="FULL" background="COLOR_LIST_BACKGROUND"/>
							</Composite>
						</TabItem>
					</TabFolder>
				</Composite>
				<Composite fill="FULL" background="COLOR_WIDGET_BACKGROUND" border="SHADOW_ETCHED_OUT">
					<Label name="DetailName" text="Name" fill="HORIZONTAL" border="SHADOW_ETCHED_OUT"/>
					<Label name="DetailDescription" text="Description" fill="HORIZONTAL" border="SHADOW_ETCHED_OUT"/>
					<Button type="CHECK" text="Madatory ?" fill="HORIZONTAL"/>
					<Group name="Type" fill="FULL">
						<Composite fill="FULL">
						</Composite>
						<Composite fill="FULL">
							<Button text="DisplayPnrElements" name="DisplayPnrElements" fill="HORIZONTAL"/>
							<Composite fill="FULL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Composite numColumns="3" fill="HORIZONTAL">
									<Label text="Transform Rules" fill="FULL"/>
									<Button name="AdditionalDocument1" text="Additional Document"/>
									<Button name="NotSupported1" text="not supported"/>
								</Composite>
								<Text name="TransformRules1" fill="FULL"/>
							</Composite>
							<Composite fill="FULL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Label text="Provider Ref" fill="HORIZONTAL"/>
								<Text name="ProviderRef1" fill="FULL"/>
							</Composite>
							<Composite fill="HORIZONTAL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Label text="Date (User)" fill="HORIZONTAL"/>
								<Text name="DateUser1" fill="HORIZONTAL" enabled="false"/>
							</Composite>
						</Composite>
						<Composite fill="FULL">
							<Button text="HidePnrElements" name="HidePnrElements" fill="HORIZONTAL"/>
							<Composite name="PnrElementsActive" fill="FULL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Label text="Pnr Elements" fill="HORIZONTAL"/>
								<Composite numColumns="3" fill="HORIZONTAL">
									<Combo name="PnrName" fill="HORIZONTAL"/>
									<Combo name="PnrAttr" fill="HORIZONTAL"/>
									<Button name="UsePnrElement" text="Use"/>
								</Composite>
								<Button name="SelfDefined" text="Create self defined method" type="CHECK" fill="HORIZONTAL"/>
								<Composite fill="FULL" numColumns="2">
									<Text name="DetailPnr" fill="FULL"/>
									<Button name="DetailPnr2" text="Detail ..."/>
								</Composite>
							</Composite>
							<Composite fill="FULL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Composite numColumns="3" fill="HORIZONTAL">
									<Label text="Transform Rules" fill="FULL"/>
									<Button name="AdditionalDocument2" text="Additional Document"/>
									<Button name="NotSupported2" text="not supported"/>
								</Composite>
								<Text name="TransformRules2" fill="FULL"/>
							</Composite>
							<Composite fill="FULL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Label text="Provider Ref" fill="HORIZONTAL"/>
								<Text name="ProviderRef2" fill="FULL"/>
							</Composite>
							<Composite fill="HORIZONTAL" border="SHADOW_ETCHED_IN" background="COLOR_LIST_BACKGROUND">
								<Label text="Date (User)" fill="HORIZONTAL"/>
								<Text name="DateUser2" fill="HORIZONTAL" enabled="false"/>
							</Composite>
						</Composite>
					</Group>
				</Composite>
			</SashForm>
		</Composite>
	</Shell>
</SWT>
